const axios = require('axios');
const { HttpsProxyAgent } = require('https-proxy-agent');
const ProxyManager = require('../services/proxy_manager');

/**
 * Executes Axios calls wrapped in residential proxies with auto-rotation.
 */
async function fetchWithRetry(url, region = 'US', maxRetries = 3) {
    let attempt = 0;
    while (attempt < maxRetries) {
        attempt++;
        const proxyUrl = ProxyManager.getProxyByRegion(region);
        const headers = ProxyManager.getSpoofedHeaders(); // Inject realistic headers
        
        console.log(`[Fetch Attempt ${attempt}] Routing through proxy: ${proxyUrl}`);
        try {
            const agent = new HttpsProxyAgent(proxyUrl);
            const response = await axios.get(url, {
                httpsAgent: agent,
                headers: headers,
                timeout: 5000
            });
            return response.data;
        } catch (error) {
            console.warn(`[Proxy Error] Attempt ${attempt} failed: ${error.message}`);
            if (error.response && error.response.status === 403) {
                console.warn(`[Proxy Blocked] 403 Forbidden detected. Immediate IP rotation...`);
            }
            if (attempt === maxRetries) throw new Error("Max proxy retries exceeded.");
        }
    }
}

/**
 * The 'Ad-Killer' Middleware
 * Strips URLs of parameters containing 'ads', 'redirect', or 'popup'.
 */
class AdKillerMiddleware {
    static cleanUrl(rawUrl) {
        if (!rawUrl) return null;
        try {
            const urlObj = new URL(rawUrl);
            const paramsToKeep = new URLSearchParams();

            for (const [key, value] of urlObj.searchParams.entries()) {
                const lowerKey = key.toLowerCase();
                const lowerVal = value.toLowerCase();
                if (
                    lowerKey.includes('ad') || lowerVal.includes('ad') ||
                    lowerKey.includes('redirect') || lowerVal.includes('redirect') ||
                    lowerKey.includes('popup') || lowerVal.includes('popup')
                ) {
                    console.log(`[AdKiller] Blocked parameter => ${key}=${value}`);
                    continue; // Skip malicious ad-tracking/redirect parameters
                }
                paramsToKeep.append(key, value);
            }
            
            // Reconstruct the clean URL
            urlObj.search = paramsToKeep.toString();
            console.log(`[AdKiller] Cleaned URL => ${urlObj.toString()}`);
            return urlObj.toString();
        } catch (e) {
            console.error('[AdKiller] Error parsing URL:', e.message);
            return rawUrl;
        }
    }
}

/**
 * Base abstract class defining the interface for all providers.
 */
class BaseProvider {
    constructor(identifier) {
        this.identifier = identifier;
    }

    // Must be implemented by child classes
    async extractStream(id) {
        throw new Error("extractStream must be implemented by subclass");
    }
}

/**
 * Template Cheerio Provider. Fast and lightweight parsing.
 */
class GenericCheerioProvider extends BaseProvider {
    constructor() {
        super('GenericCheerio');
    }

    async extractStream(id) {
        console.log(`[${this.identifier}] Attempting extraction for ID: ${id}`);
        // Demo implementation:
        // Try to fetch HTML and locate an embedded <video> or .m3u8 source
        try {
            // Using the new Failover Proxy Layer
            // let html = await fetchWithRetry(`https://example.com/watch/${id}`, 'US', 3);
            // let $ = cheerio.load(html);
            // let videoSrc = $('video > source').attr('src') || $('video').attr('src');
            // return videoSrc;
            
            // Mocking a successful extraction of an M3U8 payload.
            // In a real scenario, you parse the DOM to locate the CDN link.
            await new Promise(r => setTimeout(r, 500)); 
            
            // Simulating parsing failure if id is "fail"
            if (id === 'fail') throw new Error("Source not found in DOM");
            
            return 'https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8?ad_id=9871&redirect=tracker.com';
        } catch (error) {
            console.error(`[${this.identifier}] Extraction failed:`, error.message);
            return null; // Signals the system to try the next provider
        }
    }
}

/**
 * Template Puppeteer Provider. Use for JS-heavy sites or intercepting network requests.
 */
class GenericPuppeteerProvider extends BaseProvider {
    constructor() {
        super('GenericPuppeteer');
    }

    async extractStream(id) {
        console.log(`[${this.identifier}] Attempting extraction via headless browser...`);
        // Demo implementation:
        // Intercept XMLHttpRequest for .m3u8 manifests dynamically generated by JS
        /*
        let browser;
        try {
            browser = await puppeteer.launch({ executablePath: '/usr/bin/google-chrome' }); // Path required for core
            const page = await browser.newPage();
            let m3u8Link = null;
            
            page.on('response', response => {
                const url = response.url();
                if (url.includes('.m3u8') && !url.includes('ad')) {
                    m3u8Link = url;
                }
            });
            await page.goto(`https://js-heavy-site.com/watch/${id}`, { waitUntil: 'networkidle2' });
            return m3u8Link;
        } catch (e) {
            return null;
        } finally {
            if (browser) await browser.close();
        }
        */
        await new Promise(r => setTimeout(r, 1000));
        return 'https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8';
    }
}

/**
 * Provider System Controller
 * Handles provider registration and the failover aggregation engine.
 */
class ProviderSystem {
    constructor() {
        this.providers = [];
    }

    registerProvider(provider) {
        this.providers.push(provider);
    }

    async resolveMedia(id) {
        console.log(`[System] Resolving media for ID: ${id}`);
        // Iterate through all providers linearly
        for (const provider of this.providers) {
            const rawUrl = await provider.extractStream(id);
            
            if (rawUrl) {
                console.log(`[System] Success with provider: ${provider.identifier}`);
                // Run through ad-killer middleware
                const safeUrl = AdKillerMiddleware.cleanUrl(rawUrl);
                
                return {
                    success: true,
                    provider: provider.identifier,
                    stream: safeUrl,
                    subtitles: [
                        { lang: 'English', url: 'https://example.com/subs/en.vtt' },
                        { lang: 'Spanish', url: 'https://example.com/subs/es.vtt' }
                    ]
                };
            }
        }
        
        return {
            success: false,
            error: "All registered extractors failed or source is dead."
        };
    }
}

// Instantiate and export the ready-to-use controller
const engine = new ProviderSystem();
engine.registerProvider(new GenericCheerioProvider());
engine.registerProvider(new GenericPuppeteerProvider());

class DynamicConfigProvider extends BaseProvider {
    constructor(name, domain) {
        super(name);
        this.domain = domain;
    }
    async extractStream(id) {
        console.log(`[DynamicProvider - ${this.identifier}] Received extraction parameter for ${id} targeting ${this.domain}`);
        // Hook is functional, but payload decompilation logic inherently requires explicit design per service payload.
        // Returns null dynamically falling back to GenericCheerio scraper hook.
        return null; 
    }
}

ProviderSystem.prototype.registerDynamicProvider = function(name, rawDomain) {
    // Avoid memory leak by duplicating classes on the 24 hour sync chron
    if (!this.providers.find(p => p.identifier === name)) {
        console.log(`[System Hook] Linked new Github repository engine logic: ${name} mapped against (${rawDomain})`);
        this.registerProvider(new DynamicConfigProvider(name, rawDomain));
    }
};

// Export components so you can construct your own loklok/soap2day classes extending BaseProvider
module.exports = {
    engine,
    ProviderSystem,
    BaseProvider,
    AdKillerMiddleware
};
